### ISSUE TITLE
Uri_base to be used for generating link

### ISSUE THREAD

**Issue by mopi** [bigpresh/Dancer-Plugin-NYTProf#11] opened 2013-02-06 11:05 UTC
in line 159, the code has <a href="/nytprof..." instead it would be better to have <a href=".request->uri_base().q{/nytprof...}

so for those apps mounted in different path will work without any change in the url.

Thanks,

Mopi.

**Comment by garu** [comment] 2014-10-07 21:44
this looks like a duplicate of #6, is that correct?

**Closed as completed** 2014-10-28 19:18 UTC
